AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'keitam-blog

  Sample SAM Template for keitam-blog

  '
Globals:
  Function:
    Timeout: 5
Resources:
  TextvidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://textvid-lambda/e2828f4c95715af1718dfb49145a3b9f
      Handler: textvid
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables:
          PARAM1: VALUE
Outputs:
  TextvidAPI:
    Description: API Gateway endpoint URL for Prod environment for Textvid Function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  TextvidFunction:
    Description: Textvid Function ARN
    Value:
      Fn::GetAtt:
      - TextvidFunction
      - Arn
  TextvidFunctionIamRole:
    Description: Implicit IAM Role created for Textvid Function
    Value:
      Fn::GetAtt:
      - TextvidFunctionRole
      - Arn
