AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  keitam-blog

  Sample SAM Template for keitam-blog

Globals:
  Function:
    Timeout: 5

Resources:
  TextvidRootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: textvid
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables: &TextvidEnv
          TV_SITE_TITLE: Textvid
          TV_FOOTNOTE: Powered by [Textvid](https://github.com/keitam913/textvid)
          TV_GITHUB_API_POST_REPOSITORY_ENDPOINT: https://api.github.com/repos/keitam913/blog-posts
          TV_MODE: cloud
  TextvidSubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: textvid
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{all+}
            Method: ANY
      Environment:
        Variables:
          <<: *TextvidEnv
