AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  keitam-blog

  Sample SAM Template for keitam-blog

Globals:
  Function:
    Timeout: 5

Resources:
  AirlogRootFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: airlog
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: ANY
      Environment:
        Variables: &AirlogEnv
          PORT: 3000
          AL_SITE_TITLE: Airlog
          AL_FOOTNOTE: Powered by [Airlog](https://github.com/keitam913/airlog)
          AL_BLOG_DSN: root:root@tcp(airlog_db:3306)/blog
          AL_GITHUB_API_POST_REPOSITORY_ENDPOINT: https://api.github.com/repos/keitam913/blog-posts
  AirlogSubFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: airlog
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{all+}
            Method: ANY
      Environment:
        Variables:
          <<: *AirlogEnv
